require("plugins_setup")

require("core.options")
require("core.keymaps")
require("core.colorscheme")

require("plugins.bufferline")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.mason")
require("plugins.nvim-dap")
require("plugins.lsp")
require("plugins.tree-sitter")
require("plugins.cmp")
require("plugins.pretty-fold")
require("plugins.luasnip")
require("plugins.chafa")
