local gh = function(x) return 'https://github.com/' .. x end
vim.pack.add({
    gh('nvim-lua/plenary.nvim'),
    gh('gbprod/nord.nvim'),
    gh('aserowy/tmux.nvim'),
    gh('jdhao/better-escape.vim'),
    gh('machakann/vim-highlightedyank'),
    gh('chentoast/marks.nvim'),
    gh('michaeljsmith/vim-indent-object'),
    gh('tpope/vim-sleuth'),
    gh('kyazdani42/nvim-web-devicons'),
    gh('kylechui/nvim-surround'),
    gh('hrsh7th/nvim-cmp'),
    gh('neovim/nvim-lspconfig'),
    gh('L3MON4D3/LuaSnip'),
    gh('rafamadriz/friendly-snippets'),
    gh('echasnovski/mini.align'),
    gh('numToStr/Comment.nvim'),
    gh('lewis6991/gitsigns.nvim'),
    gh('nvim-telescope/telescope-fzf-native.nvim'),
    gh('nvim-telescope/telescope.nvim'),
    gh('debugloop/telescope-undo.nvim'),
    gh('nvim-treesitter/nvim-treesitter'),
    gh('nvim-treesitter/nvim-treesitter-textobjects'),
    gh('stevearc/oil.nvim'),
})
return true
